[package]
name = "common-raw"
version = "0.1.0"
authors = ["handsome0hell <handsome0hell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molecule = { version = "0.6", default-features = false }
